### ISSUE TITLE
Command tests takes ages

### ISSUE THREAD

**Issue by rnixx** [sde1000/python-dali#18]
Running tests like so:

    ~/workspace/python-dali$ ./bin/python -m dali.test_command
    ....
    ----------------------------------------------------------------------
    Ran 4 tests in 85.095s

There's no USB DALI adapter connected while running the tests, so this might be a problem but then it would be better to have a backend mock for these tests.

**Comment by sde1000** [comment]
The reason it takes a long time is because the strategy for testing is very basic.

The slowest test routine goes through each possible 16-bit DALI commands and makes sure it can be decoded into a Command object instance - and then takes that object instance and makes sure it encodes back to the same DALI command.

Then it does it for each of the first ten device types.

This has been very useful for getting full test coverage of all the subclasses of Command, and has caught many bugs.

An improvement would be to restrict the tests for device types other than zero to the portion of the DALI command space that they occupy.  This would probably speed up the tests by nearly ten times.

**Comment by sde1000** [comment]
NB it may be possible to speed up the command tests further by restricting the test pattern even more.  The hard bit is doing this while keeping coverage.
