### ISSUE TITLE
Another DALI driver

### ISSUE THREAD

**Issue by rnixx** [sde1000/python-dali#48]
Since there's some drive about DALI drivers at the moment i want to place my latest finding here as well

https://git.unipi.technology/UniPi/unipi-python-lighting/blob/master/UnipiDali/unipidali.py

maybe it ends up in the driver collection somewhen

**Comment by mhemeryck** [comment]
Had a similar question: if I would submit a PR for including it here, would you pull it in?

I so, I will also bring the ppl from [unipi](https://www.unipi.technology/) in the loop.

**Comment by rnixx** [comment]
You might check whether license is ok (LGPL). Then i think there's no reason not to merge. @sde1000 ?

**Comment by sde1000** [comment]
I'm away on holiday at the moment, I'll have a look next Tuesday.

**Comment by mhemeryck** [comment]
No sweat, I'm only starting to look into DALI right now, might take some time to actually create the PR.

On a side note, I was also considering to prettify the code a bit: automated linting, pinning dependencies, ... How do you feel about this? Probably a different topic / issue ...

**Comment by rnixx** [comment]
@mhemeryck please do not mix features an cleanup. btw - this package has no dependencies

**Comment by mhemeryck** [comment]
I agree to not mix this feature with any possible cleanup -- I'll first look into the unipi driver (since I'll actually need that one quite soon).

On the dependency note: I did notice you were using the package `usb` somewhere, which isn't a standard python package. I assume it's [`pyusb`](https://pypi.org/project/pyusb/)? Anyways, I will try to get back to that in another topic like you suggested. I just already noted it since I couldn't run that project directly.

**Comment by rnixx** [comment]
@mhemeryck ah right, yes. pyusb is needed for hasseb and tridonic drivers, my fault.

If you're further interested to contribute, there's another driver left to be adopted to the correct API (#54).
