### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by beireken** [sde1000/python-dali#53]
I'm very interested in this project but i'm not exactly sure what i can do with this.
When i buy a hasseb usb adapter, can i use this to assign an adress to new balasts  (i guess i can do this with the hasseb software) and then switch / dim these?
How can i interface with the library (node-red, home-assistant)?
Is anyone using this with home-assistant or any other software to control their lighting?

**Comment by dgomes** [comment]
I initially setup the addresses using the basses software, although you can use this library to achieve the same.

Personally I've used an Hasseb controller connected directly to my Home-Assistant (running on a RPi) setup using a custom-component: 
https://github.com/dgomes/home-assistant-custom-components/tree/master/light

and more recently I've moved to https://github.com/dgomes/dali2mqtt since I've went from using an RPi to using a VM for running my Home-Assistant setup.

**Comment by beireken** [comment]
Ok, thx a lot! Good info!

**Comment by rnixx** [comment]
This issue might be closed.
